export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '@/styles/globals.css'
import TranslateController from '@/ui/TranslateController'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TranslateController>
          {children}
        </TranslateController>
      </body>
    </html>
  )
}
